"""test

Revision ID: 5418bb08b3e6
Revises: 6d6f6a4cb5ed
Create Date: 2026-08-10 00:00:34.518674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5418bb08b3e6'
down_revision: Union[str, None] = '6d6f6a4cb5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
